name: Minecraft Server on GitHub

on:
  workflow_dispatch: # Actions tab se manually start karne ke liye

jobs:
  run-mc-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Server and Playit
        run: |
          # Server file download (1.20.4 Paper)
          curl -o server.jar https://api.papermc.io/v2/projects/paper/versions/1.20.4/builds/497/downloads/paper-1.20.4-497.jar
          echo "eula=true" > eula.txt
          
          # Playit.gg Stable Version (GitHub ke liye best)
          curl -Lo playit https://github.com/playit-cloud/playit-agent/releases/download/v0.15.13/playit-linux-amd64
          chmod +x playit

      - name: Run Playit Agent
        run: |
          # Apni secret key ke saath background mein run karein
          ./playit --secret e58dd831126be724b46bc310df370deee0c517a18a49364837e8e51e5d24de53 run &
          sleep 20

      - name: Start Minecraft Server
        run: |
          java -Xmx7G -Xms7G -jar server.jar nogui
